# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_cs_model <- function() {
    invisible(.Call('_RadEro_rcpp_cs_model', PACKAGE = 'RadEro'))
}

